[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/verify"
  to = "/verify.html"
  status = 200

[[redirects]]
  from = "/five-a-day"
  to = "/five-a-day.html"
  status = 200
